edition = "2021"
match_block_trailing_comma = true
force_multiline_blocks = true
struct_lit_single_line = false
trailing_comma = "Vertical"
# This is only necessary until rustfmt 1.4.11 is used.
skip_children = true
